//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan_Phim
    {
        public string TenNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public int DanhGia { get; set; }
        public int BLId { get; set; }
        public int IdPhim { get; set; }
    }
}
