//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int Id { get; set; }
        public Nullable<int> IdPhim { get; set; }
        public Nullable<int> IdTK { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDang { get; set; }
        public bool TinhTrang { get; set; }
        public int DanhGia { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
