//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public int id { get; set; }
        public string TenDanhMuc { get; set; }
        public Nullable<int> id_Phim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
