//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Data : DbContext
    {
        public Data()
            : base("name=Data")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CaChieu> CaChieux { get; set; }
        public virtual DbSet<DatVe> DatVes { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<LichChieu> LichChieux { get; set; }
        public virtual DbSet<LoaiGhe> LoaiGhes { get; set; }
        public virtual DbSet<LoaiPhim> LoaiPhims { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Suatchieu> Suatchieux { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTin> ThongTins { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<BinhLuan_Phim> BinhLuan_Phim { get; set; }
        public virtual DbSet<ghe_phong> ghe_phong { get; set; }
        public virtual DbSet<tkdt> tkdts { get; set; }
        public virtual DbSet<tkdttp> tkdttps { get; set; }
        public virtual DbSet<tkdttp1> tkdttp1 { get; set; }
        public virtual DbSet<Ve_LC_Phim> Ve_LC_Phim { get; set; }
        public virtual DbSet<Ve_LC_Phim_TK> Ve_LC_Phim_TK { get; set; }
    }
}
