//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghe_phong
    {
        public int Id { get; set; }
        public string TenPhong { get; set; }
        public int SoLuong { get; set; }
        public int SoluongHang { get; set; }
        public int Soluongghemoihang { get; set; }
        public bool TrinhTrang { get; set; }
        public string MoTa { get; set; }
    }
}
