//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int Id { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public string Thu { get; set; }
        public Nullable<decimal> Phuthulc { get; set; }
        public Nullable<int> IdPhim { get; set; }
        public Nullable<int> IdCC { get; set; }
        public Nullable<int> IdSC { get; set; }
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public Nullable<int> IdPhong { get; set; }
    
        public virtual CaChieu CaChieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual Suatchieu Suatchieu { get; set; }
    }
}
