//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.LichChieux = new HashSet<LichChieu>();
            this.Ves = new HashSet<Ve>();
        }
    
        public int Id { get; set; }
        public string TenPhim { get; set; }
        public string AnhPhim { get; set; }
        public int ThoiLuong { get; set; }
        public string MoTa { get; set; }
        public bool TinhTrang { get; set; }
        public string IdLoaiPhim { get; set; }
        public string DienVien { get; set; }
        public string DaoDien { get; set; }
        public System.DateTime NgayCongChieu { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string NamPhatHanh { get; set; }
        public string ChatLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
