//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int Id { get; set; }
        public Nullable<int> IdTaiKhoan { get; set; }
        public Nullable<int> IdPhim { get; set; }
        public Nullable<int> IdGhe { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> IdLC { get; set; }
        public Nullable<int> IdKM { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual LichChieu LichChieu { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
