//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve_LC_Phim_TK
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public int Id_tk { get; set; }
        public string TenPhong { get; set; }
        public string TenPhim { get; set; }
        public string TenGhe { get; set; }
        public string TenLoai { get; set; }
        public Nullable<decimal> GiaVe { get; set; }
        public Nullable<decimal> phuthusc { get; set; }
        public Nullable<decimal> Phuthulc { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public string TenLoaiGhe { get; set; }
        public string TenSuat { get; set; }
        public string Thu { get; set; }
        public int IDTK { get; set; }
    }
}
